#!/usr/bin/env node
/**
 * Bundle MCP Apps into TypeScript exports.
 *
 * This script:
 * 1. Runs Vite to build the visualizer app as a single HTML file
 * 2. Reads the built HTML
 * 3. Exports it as a TypeScript string in visualizer.ts
 *
 * Run with: npm run build:apps
 */

import { readFileSync, writeFileSync, existsSync } from "fs";
import { execSync } from "child_process";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const rootDir = resolve(__dirname, "..");

async function bundleApps() {
  console.log("Building MCP Apps with Vite...");

  try {
    // Run Vite build
    execSync("npx vite build --config vite.config.apps.ts", {
      cwd: rootDir,
      stdio: "inherit",
    });

    // Read the built HTML
    const htmlPath = resolve(rootDir, "dist/apps/index.html");
    if (!existsSync(htmlPath)) {
      console.error("Error: Built HTML file not found at", htmlPath);
      process.exit(1);
    }

    const html = readFileSync(htmlPath, "utf-8");

    // Generate TypeScript export
    const tsContent = `/**
 * Bundled HTML for the data visualizer MCP App.
 *
 * This file is auto-generated by scripts/bundle-apps.ts
 * DO NOT EDIT MANUALLY.
 *
 * Rebuild with: npm run build:apps
 */
export const visualizerHtml = ${JSON.stringify(html)};
`;

    // Write to visualizer.ts
    const outputPath = resolve(rootDir, "src/server/mcp/apps/visualizer.ts");
    writeFileSync(outputPath, tsContent);

    console.log("Successfully bundled visualizer app to", outputPath);
  } catch (error) {
    console.error("Error bundling apps:", error);
    process.exit(1);
  }
}

bundleApps();
