#!/usr/bin/env node
/**
 * Bundle Apps into TypeScript exports.
 *
 * This script:
 * 1. Runs Vite to build each app as a single HTML file
 * 2. Reads the built HTML
 * 3. Exports it as a TypeScript string
 *
 * Run with: npm run build:apps
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync } from "fs";
import { execSync } from "child_process";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const rootDir = resolve(__dirname, "..");

interface AppConfig {
  name: string;
  outputFile: string;
  varName: string;
  description: string;
}

const apps: AppConfig[] = [
  {
    name: "visualizer",
    outputFile: "src/server/mcp/apps/visualizer.ts",
    varName: "visualizerHtml",
    description: "Bundled HTML for the data visualizer MCP App.",
  },
  {
    name: "browser-app",
    outputFile: "src/browser/browser-app.ts",
    varName: "browserAppHtml",
    description: "Bundled HTML for the ontology browser/review UI.",
  },
];

async function bundleApps() {
  console.log("Building apps with Vite...\n");

  // Ensure dist/apps directory exists
  const distAppsDir = resolve(rootDir, "dist/apps");
  if (!existsSync(distAppsDir)) {
    mkdirSync(distAppsDir, { recursive: true });
  }

  for (const app of apps) {
    console.log(`Building ${app.name}...`);
    
    try {
      // Run Vite build for this app
      execSync(`APP=${app.name} npx vite build --config vite.config.apps.ts`, {
        cwd: rootDir,
        stdio: "inherit",
        env: { ...process.env, APP: app.name },
      });

      // Read the built HTML
      const htmlPath = resolve(rootDir, "dist/apps/index.html");
      if (!existsSync(htmlPath)) {
        console.error(`Error: Built HTML file not found at ${htmlPath}`);
        process.exit(1);
      }

      const html = readFileSync(htmlPath, "utf-8");

      // Generate TypeScript export
      const tsContent = `/**
 * ${app.description}
 *
 * This file is auto-generated by scripts/bundle-apps.ts
 * DO NOT EDIT MANUALLY.
 *
 * Rebuild with: npm run build:apps
 */
export const ${app.varName} = ${JSON.stringify(html)};
`;

      // Write to output file
      const outputPath = resolve(rootDir, app.outputFile);
      writeFileSync(outputPath, tsContent);

      console.log(`✓ Successfully bundled ${app.name} to ${app.outputFile}\n`);
    } catch (error) {
      console.error(`Error bundling ${app.name}:`, error);
      process.exit(1);
    }
  }

  console.log("All apps bundled successfully!");
}

bundleApps();
